# Generated by Django 3.0.1 on 2020-01-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='images/')),
                ('product_name', models.TextField()),
                ('product_price', models.FloatField()),
                ('product_category', models.TextField()),
            ],
        ),
    ]
